zahraa's review
Northwest-content/flutter_m4_stateful_widget pull request #1
Opened 2022-06-12 08:39 UTC by ZhraaBaharAluloom

- The review of both  `01_dynamic_profile_page` &  `02_Input_fields_BMI_calculator` was completed, but the third one was not yet (the dice game). However, everything was pushed for the sake of time.

- The starter point of both `dynamic_profile_page` &  `Input_fields_BMI_calculator` is not working, I think it's outdated, couldn't figure out how to solve it, I've tried many solutions but none of them worked. I created a new flutter project for both, let me know if  that can help

2022-06-29 00:20 UTC, Lailz requested changes
@ZhraaBaharAluloom

2022-06-29 00:20 UTC, Lailz commented on 01_dynamic_profile_page/01_Introduction.md
> +As you see, there are three fields (Name, Gender, and Hobbies), and this time, we will add an age field using a variable.
As you can see, there are three fields: Name, Gender, and Hobbies. We will add an age field using a variable.

2022-06-29 00:20 UTC, Lailz commented on 01_dynamic_profile_page/02_Creating_variables.md
> +3. Below the **Hobbies**'s Text widget, create a new `Text` widget responsible for showing the age.
**Hobbies** Text widget, -> with the 's

2022-06-29 00:20 UTC, Lailz commented on 01_dynamic_profile_page/03_Use_the_variables_inside_widget.md
> +> **Note:** You will see red squiggles under the age variable inside the Text widget, and if you hover over it, the VS code will tell you that “The argument type 'double' can't be assigned to the par
VS code without "the"

2022-06-29 00:20 UTC, Lailz commented on 01_dynamic_profile_page/03_Use_the_variables_inside_widget.md
> +- First option: use the **toString()** method.
Add 1. Instead of first, second option

2022-06-29 00:20 UTC, Lailz commented on 01_dynamic_profile_page/03_Use_the_variables_inside_widget.md
> +- Second option (Recommended): use the dollar sign **$**.
2. Use the dollar sign **$** (Recommended)

2022-06-29 00:20 UTC, Lailz commented on 02_Input_fields_BMI_calculator/02_TextField_widget.md
> +1. To calculate the BMI, you need the user to fill two inputs: height and weight. To do that, use a `TextField` widget which helps you to get inputs from the user.
`TextField` widget to help you get inputs from the user.

2022-06-29 00:20 UTC, Lailz commented on 02_Input_fields_BMI_calculator/02_TextField_widget.md
> +> > d. The **decoration** named argument is used to add style to the **TextField**. And this named argument takes an **InputDecoration()** object, which helped us to add:
- Don't start a sentence with and
- which helped us to add -> remove to

2022-06-29 00:20 UTC, Lailz commented on 02_Input_fields_BMI_calculator/02_TextField_widget.md
> +3. Duplicate the whole **`TextField`**'s Container of the height to add another **`TextField`** widget for the weight, paste it under the height widget directly, change the **hintText** from “Height
directly. Change the

2022-06-29 00:20 UTC, Lailz commented on 02_Input_fields_BMI_calculator/02_TextField_widget.md
> +4. Add an `ElevatedButton` widget which helps the user to calculate the BMI, and shows the result when clicked.
calculate the BMI, and shows the result when clicked.

- show not shows
- remove the ,

2022-06-29 00:20 UTC, Lailz commented on 02_Input_fields_BMI_calculator/03_TextEditingController.md
> +13. Create a function that takes the **bmi** variable, and converts it to a status such as Fat, Normal, or Thin based on some conditions.
such as Fat, Normal, or Thin 

should be Underweight, Normal, Overweight

2022-06-29 00:20 UTC, Lailz commented on 02_Input_fields_BMI_calculator/03_TextEditingController.md
> +> Here, we created a `bmiStatus` function that takes one double argument, and returns a String. In our case, it will take the bmi value. If it is less than or equal to 20, it will return ‘Thin’ Strin
Thin -> Underweight
Fat -> Overweight

2022-06-29 00:20 UTC, Lailz commented on 02_Input_fields_BMI_calculator/03_TextEditingController.md
> +To fix what happens, we will add the `if condition` above the Container Image widget.
To fix this issue or what happened

2022-07-02 11:02 UTC, ZhraaBaharAluloom commented on 01_dynamic_profile_page/02_Creating_variables.md
> +3. Below the **Hobbies**'s Text widget, create a new `Text` widget responsible for showing the age.
you mean without  not with right?

2022-07-02 11:28 UTC, ZhraaBaharAluloom commented on 02_Input_fields_BMI_calculator/02_TextField_widget.md
> +3. Duplicate the whole **`TextField`**'s Container of the height to add another **`TextField`** widget for the weight, paste it under the height widget directly, change the **hintText** from “Height
These are consecutive steps, so I thought it makes more sense to keep them linked (duplicate, paste, change and change)

2022-07-02 12:33 UTC, merged